[package]
name = "cinerepak"
version = "0.1.0"
authors = ["Misty De Meo <mistydemeo@gmail.com>"]

[dependencies]
clap = "2.24.2"
sega_film = { git = "https://github.com/mistydemeo/sega_film.git", rev = "5087b731524e0fb07cdf8bddccfad321cd117856" }
